## Input

This web application uses a simplified set of root and soil input parameters to quickly generate a series of root diameters, orientations etc. The required model input is inputted under several tabs. Input relating to roots is specified under the tabs 'Root diameters', 'Root orientations' and 'Root properties', while input for the soil (strengths, stresses, shear zone thicknesses, shear displacements etc.) are specified under the tab 'Soil properties'. Automatically updating plots are displayed in the input tabs to help visualise the user input.

### Unit system

The user can select below what definitions to use for:

* all length scales (e.g. root diameter, root length, shear displacement, shear zone thickness)
* all root stresses, strenghts and stiffnesses (e.g. root tensile stress and strength), 
* all soil stresses, strengths and stiffnesses (e.g. soil stress, root reinforcement, peak root reinforcement)
* root strains (e.g. root tensile strain)
* root area ratio 
* the root reference diameter $d_{r,0}$, which is required for the various power-law relationships between root diameter and (for example) root tensile strength used in the model.

All angles are expressed in degrees. Please note that when the unit system is  *changed*, all input parameters of that type are reset to their default values! 
